### ISSUE TITLE
Upgrade to v1.7.0 broke the e2e tests in Stackrox

### ISSUE THREAD

**Issue by vikin91** [np-guard/cluster-topology-analyzer#199]
Hello :wave:
I see that the recent update from v1.6.0 to 1.7.0 has changed the error messages and our e2e tests are failing now - see https://github.com/stackrox/stackrox/pull/5793 

There are two possibilities to fix that:
- Restore previous error messages to keep the compatibility with the tests
- Update the test assertions in Stackrox repo

Both of these solutions are equally fine. I am open for questions if there are any.

**Comment by zivnevo** [comment]
A better fix would be to change the test assertions in Stackrox repo so they check error **type** rather than error string.
Do you want me to commit a fix to the `dependabot/go_modules/github.com/np-guard/cluster-topology-analyzer-1.7.0` branch, or should this be a separate PR?

**Comment by vikin91** [comment]
The problem is that these are e2e tests and they operate on strings printed to console and do not have access to the go code. 
I think both options are fine - if pushing to that branch does not work, then you can open a separate PR for this.

**Comment by zivnevo** [comment]
Opened [PR #5877](https://github.com/stackrox/stackrox/pull/5877)

**Comment by zivnevo** [comment]
Fixed in Stackrox e2e tests.
