### ISSUE TITLE
No output for unknown kinds

### ISSUE THREAD

**Issue by esnible** [np-guard/cluster-topology-analyzer#73]
I tried np-guard against Istio bookinfo:

```bash
./bin/net-top -dirpath ~/go/src/istio.io/istio/samples/bookinfo/platform/kube \
   -commitid 71ea0bdf1cfc5e9d9918094368525dbedee453fc \
   -giturl https://github.com/istio/istio -gitbranch master
```

The output is a backtrace:

```bash
2022-08-24T16:02:15.464-0400	WARN	controller/utils.go:118	no kind "ClusterIssuer" is registered for version "certmanager.k8s.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100"
github.com/np-guard/cluster-topology-analyzer/pkg/controller.parseK8sYaml
	/Users/snible/go/src/github.com/np-guard/cluster-topology-analyzer/pkg/controller/utils.go:118
github.com/np-guard/cluster-topology-analyzer/pkg/controller.getK8sDeploymentResources
	/Users/snible/go/src/github.com/np-guard/cluster-topology-analyzer/pkg/controller/utils.go:78
github.com/np-guard/cluster-topology-analyzer/pkg/controller.extractConnections
	/Users/snible/go/src/github.com/np-guard/cluster-topology-analyzer/pkg/controller/engine.go:76
github.com/np-guard/cluster-topology-analyzer/pkg/controller.Start
	/Users/snible/go/src/github.com/np-guard/cluster-topology-analyzer/pkg/controller/engine.go:23
main.runAnalysis
	/Users/snible/go/src/github.com/np-guard/cluster-topology-analyzer/cmd/nettop/main.go:30
main.main
	/Users/snible/go/src/github.com/np-guard/cluster-topology-analyzer/cmd/nettop/main.go:39
```

Perhaps np-guard should skip such files, or offer guidance on how to handle them.

**Comment by esnible** [comment]
The JSON output is generated.  I only reported the backtrace.

The output would be improved if I knew what was being complained.  For example, the output includes:
`2022-08-25T11:20:57.162-0400	INFO	controller/utils.go:122	Skipping object with type: Ingress`

It would be better if it it said "Skipping object with type: Ingress *in file bookinfo-ingress.yaml*.

I would prefer if it said INFO Skipping unsupported object with kind "ClusterIssuer" is for "certmanager.k8s.io/v1alpha1" in bookinfo-certificate.yaml" rather than issuing the Warning.

I suspect that ClusterIssuer is a real type that you haven't compiled in.  You could compile it in perhaps using `import _ "k8s.io/api/certificates"` but that just increases the size of the binary.

**Comment by zivnevo** [comment]
Logging was much improved:
* No backtraces
* File info added for many log messages
* New command-line flags control verbosity: `-q` for quiet mode and `-v` for verbose mode
